### PR TITLE
Fix for vehicle "isMoving" and position to return correctly regardles…

### PR DESCRIPTION
**Pull request by Farfar**
Changed so that vehicleMoving is always supported if position is supported. And position is supported even if vehicle is moving when component is initialized.
…s of movement or no

	ändrad:        skodaconnect.py

### CODE REVIEW

**Comment by lendy007** [comment]
Hi @Farfar - just half hour ago I commited fix for this as well so I think this pull request is no more needed...

But what I see in logs after last commit - when car was parked and then it started to move, next update will correctly update vehicleMoving attribute, but for some reason it is also trying to get position even when is_position_supported is false, but maybe capabilities are loaded only during first load? I don't know how to proceed with that, would you have some idea?

```
2020-11-27 08:24:55 DEBUG (MainThread) [custom_components.skodaconnect.binary_sensor] Getting state of vehicleMoving
2020-11-27 08:24:55 DEBUG (MainThread) [custom_components.skodaconnect.device_tracker] Getting location of Kodiaq
2020-11-27 08:24:56 ERROR (MainThread) [homeassistant.util.logging] Exception in see_vehicle when dispatching 'skodaconnect.updated': ()
Traceback (most recent call last):
  File "/config/custom_components/skodaconnect/device_tracker.py", line 34, in see_vehicle
    gps=instrument.state,
  File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 263, in state
    state = super().state or {}
  File "/usr/local/lib/python3.8/site-packages/dashboardskoda.py", line 58, in state
    return self.vehicle.get_attr(self.attr)
  File "/usr/local/lib/python3.8/site-packages/skodaconnect.py", line 680, in get_attr
    return find_path(self.attrs, attr)
  File "/usr/local/lib/python3.8/site-packages/utilities.py", line 86, in find_path
    return find_path(src[path[0]], path[1:])
KeyError: 'position'
 
```

**Comment by Farfar** [comment]
I added an easy fix that should take care of that. Check out the diff!
This way should reliably return correct values when vehicle is moving: No data from def position and True from def vehicleMoving.

**Comment by lendy007** [comment]
Ah! Great idea, thank you! Shouldn't it be `if not self.vehicleMoving:` ? Without self I was getting error, that vehicleMoving isn't defined... Testing now with self and if working I will release :)

**Comment by lendy007** [comment]
Ok, now it works without exception, it just shows warning:

`2020-11-27 09:48:56 WARNING (MainThread) [homeassistant.components.device_tracker] Could not parse gps value for kodiaq: ('?', '?', None, None, None)`

but position is somehow wrong. I would expect it will show Unknown, but it cycles between Home & Away :(

**Comment by Farfar** [comment]
> Ah! Great idea, thank you! Shouldn't it be `if not self.vehicleMoving:` ? Without self I was getting error, that vehicleMoving isn't defined... Testing now with self and if working I will release :)

I was a bit hasty I see, of course self.vehicleMoving is correct :)

> Ok, now it works without exception, it just shows warning:
> 
> `2020-11-27 09:48:56 WARNING (MainThread) [homeassistant.components.device_tracker] Could not parse gps value for kodiaq: ('?', '?', None, None, None)`
> 
> but position is somehow wrong. I would expect it will show Unknown, but it cycles between Home & Away :(

I reverted some changes and did a new take on this. I thought hass would report position as unknown but this apparently raised some issues.
The problem before I think was that the vehicleDataResponse gets overwritten with only "isMoving". With latest commit the old position data should remain until the car comes to a stop.

**Comment by lendy007** [comment]
I published 1.0.16 so let's see how it behaves... I have put a note about possible issues with device_tracker, but when used in combination with vehicleMoving=no, then it should be OK...

**Comment by Farfar** [comment]
> I published 1.0.16 so let's see how it behaves... I have put a note about possible issues with device_tracker, but when used in combination with vehicleMoving=no, then it should be OK...

If you move the "isMoving" content to its own key instead of "findCarResponse" then the positional data should be intact between updates (just no new position data until stopped) and you can revert the isMoving check in def position.

**Comment by Farfar** [comment]
I have tested this latest commit and it is working for me. The moving state is displayed correctly and the device tracker doesn't get new GPS data until the car stops (old data persists until stop)

**Comment by lendy007** [comment]
Ok, even when it is not ideal (to have old data when car is moving), it is definitely better than switching between Away&Home every refresh because it would trigger change of position which is not correct... As your code seems to be far away from mine now, I will include changes manually and release :) Thank you!

**Pull request closed without merging**
