### PR TITLE
Fixed weekday bug in vehicle.py

### PR DESCRIPTION
**Pull request by markblokpoel**
Line 628 contained incorrect reference to day, renamed it to weekdays. Should now return the correct schedule array.

I have not been able to test any of this, since I don't know how to incorporate the code edit in my home assistant instance.

### CODE REVIEW

**Comment by Farfar** [comment]
I have reviewed the code but the "days" variable should be correct. The string sent to the API should be in the "yynnyny" format.

**Comment by markblokpoel** [comment]
Ok, but then the logic is still faulty. It currently filters only the ‘y’ and hence returns incorrect strings. E.g. yynnyny become yyyy. My logs confirm this, see [this issue](https://github.com/lendy007/homeassistant-skodaconnect/issues/120).

**Comment by markblokpoel** [comment]
I looked at the code again, didn't have time in a while, sorry. I believe that the check on line 627 in vehicle.py needs to be roved. If you look at the debug info in the post linked above you can see that this check basically filters all 'n's from the array. But as you correctly mentioned, the api expects a length 7 array. Do you want me to create a pull request for this?

**Comment by Farfar** [comment]
I will reopen this and take a look in the near future now when I have some spare time

**Comment by Farfar** [comment]
Closing this PR since the change is incorporated since a while back.

**Pull request closed without merging**
