### PR TITLE
Locking fixes. Correct URL for SPIN based on homeregion

### PR DESCRIPTION
**Pull request by tanelvakker**
Use userlocation host for SPIN requests. Implement SPIN URL differentiation

### CODE REVIEW

**Comment by Farfar** [comment]
Looking good! But shouldn't the api endpoint urls be without starting '/' ?
Not sure but since all other urls are without starting '/' I think the sec url will be with double /?

**Comment by tanelvakker** [comment]
>>> urljoin('http://localhost/','/test')
'http://localhost/test'

**Comment by Farfar** [comment]
Top!

**Review by lendy007 — APPROVED** [review]
Great job!

**Pull request merged**
