### PR TITLE
Added Window-Heater Handling for Skoda Enyaq

### PR DESCRIPTION
**Pull request by scoutice**
Added special handling for Skoda Enyaq to read the window heating status
* added attributes to window_heater for front and rear window
* read current status from airConditioning/windowsHeatingStatuses instead of airConditioningSettings/windowsHeatingEnabled

Note: airConditioningSettings/windowsHeatingEnabled has been used before. as it it not clear, if this is needed by some car, it was kept and priorizied below the new code

### CODE REVIEW

**Review by Farfar — COMMENTED** [review]
The changes to dashboard.py is good for including the attributes of the window heater. It will only benefit the Enyaq though since the attributes included only will get populated for the Enyaq. Keep in mind that the Enyaq is hosted on it's own API (so far) and all other connected Skoda cars are hosted on another API with different endpoints and data structures.
The change would remove the timestamp attribute of when start/stop climatisation was last triggered and the result without adding anything new.
A better way to add the front and rear window heating attributes for the Enyaq would be to create a check if the attributes are supported and then include them as well.

**Comment by Farfar** [comment]
Overall a good addition. I will review the code some more to try and have the same functionality but with fewer rows of code.

**Comment by Farfar** [comment]
> shall i add the last_result and last_timestamp again and re-pull or do you merge the code?

I'll readd when I merge 👍🏻

**Comment by scoutice** [comment]
oh, sorry, i just saw that my tests for git (commit within eclipse, add and delete files) seem to be forwarded to the whole pull-request i made.

**Review by Farfar — COMMENTED** [review]
Overall I think this looks good now, thanks for your help!

**Pull request merged**
